# Generated by Django 3.2.25 on 2026-03-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=64, verbose_name='来源IP')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='请求时间')),
                ('device_id', models.CharField(default='', max_length=64, verbose_name='设备ID')),
                ('iridiumid', models.CharField(default='', max_length=64, verbose_name='铱星号')),
                ('sensorflag', models.CharField(default='', max_length=32, verbose_name='传感器标志位')),
                ('packet_len', models.IntegerField(default=0, verbose_name='包长')),
                ('result', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='failed', max_length=16, verbose_name='处理结果')),
                ('ingest_status', models.CharField(choices=[('ingested', '入库'), ('not_ingested', '未入库')], default='not_ingested', max_length=16, verbose_name='入库状态')),
                ('message', models.CharField(default='', max_length=255, verbose_name='处理说明')),
                ('raw', models.TextField(blank=True, default='', verbose_name='原始内容')),
                ('db_time', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '数据接收记录',
                'verbose_name_plural': '数据接收记录',
                'db_table': 't_receive_log',
                'ordering': ['-id'],
            },
        ),
    ]
