# Generated by Django 3.2.25 on 2026-03-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivelog',
            name='parse_result',
            field=models.TextField(blank=True, default='', verbose_name='解析结果'),
        ),
        migrations.AddField(
            model_name='receivelog',
            name='sn',
            field=models.IntegerField(default=0, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='receivelog',
            name='result',
            field=models.CharField(choices=[('recv_failed', '接收失败'), ('parse_failed', '解析失败'), ('db_failed', '入库失败'), ('completed', '处理完成')], default='failed', max_length=16, verbose_name='处理阶段'),
        ),
    ]
