# Generated by Django 3.2.25 on 2026-02-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='设备ID', max_length=64, unique=True, verbose_name='设备ID')),
                ('device_name', models.CharField(help_text='设备名称', max_length=100, verbose_name='设备名称')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('status', models.IntegerField(default=0, help_text='0: 离线, 1: 在线', verbose_name='状态')),
                ('is_delete', models.IntegerField(default=0, help_text='0: 未删除, 1: 已删除', verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备基础信息',
                'verbose_name_plural': '设备基础信息',
                'db_table': 't_device_info',
                'ordering': ['-create_time'],
            },
        ),
    ]
