# Generated by Cursor on 2026-02-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='area_name',
            field=models.CharField(default='亚太', max_length=50, verbose_name='区域名称'),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='device_type',
            field=models.CharField(choices=[('buoy', '浮标'), ('station', '气象站')], default='buoy', max_length=20, verbose_name='设备类型'),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='last_report_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后上报时间'),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='经度'),
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.BigIntegerField(blank=True, null=True, verbose_name='包序号')),
                ('packet_time', models.DateTimeField(verbose_name='数据时间')),
                ('iridium_id', models.CharField(blank=True, default='', max_length=255, verbose_name='铱星编号')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='经度')),
                ('board_voltage', models.FloatField(blank=True, null=True, verbose_name='板子电压')),
                ('board_temp', models.FloatField(blank=True, null=True, verbose_name='板子温度')),
                ('air_temp', models.FloatField(blank=True, null=True, verbose_name='空气温度')),
                ('air_humid', models.FloatField(blank=True, null=True, verbose_name='空气湿度')),
                ('atmosphere', models.FloatField(blank=True, null=True, verbose_name='大气压力')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='风速')),
                ('wind_direct', models.FloatField(blank=True, null=True, verbose_name='风向')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='原始扩展数据')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_list', to='device.deviceinfo', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备业务数据',
                'verbose_name_plural': '设备业务数据',
                'db_table': 't_device_data',
                'ordering': ['-packet_time', '-id'],
            },
        ),
    ]
