# Generated by Django 3.2.25 on 2026-03-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('imap_host', models.CharField(default='imap.163.com', max_length=120)),
                ('imap_port', models.IntegerField(default=993)),
                ('auth_code', models.CharField(max_length=512)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '邮箱账号',
                'verbose_name_plural': '邮箱账号',
                'db_table': 'email_account',
            },
        ),
        migrations.CreateModel(
            name='EmailAttachmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('email_id', models.CharField(db_index=True, max_length=128)),
                ('subject', models.TextField(default='')),
                ('folder_name', models.CharField(default='', max_length=128)),
                ('file_name', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='success', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '邮箱附件日志',
                'verbose_name_plural': '邮箱附件日志',
                'db_table': 'email_attachment_log',
            },
        ),
        migrations.CreateModel(
            name='EmailTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('action', models.CharField(max_length=50)),
                ('request_params', models.TextField(default='')),
                ('result', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '邮箱任务日志',
                'verbose_name_plural': '邮箱任务日志',
                'db_table': 'email_task_log',
            },
        ),
    ]
