# Generated by Django 4.2.28 on 2026-02-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='用户名', max_length=100, verbose_name='用户名')),
                ('password', models.CharField(help_text='密码', max_length=100, verbose_name='密码')),
                ('type', models.IntegerField(choices=[(1, '超级管理员'), (2, '客户')], default=1, verbose_name='用户类型')),
                ('device_list', models.JSONField(default=list, help_text='设备列表', verbose_name='设备列表')),
                ('is_delete', models.IntegerField(default=0, help_text='0: 未删除, 1: 已删除', verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 't_user',
                'ordering': ['-create_time'],
            },
        ),
    ]
